---
title: "DataFest"
listing:
  contents: datafest_file
  sort: "date desc"
  type: default
  categories: true
  sort-ui: false
  filter-ui: false
page-layout: full
title-block-banner: false
execute:
  cache: false
---

DataFest is a competition of data in which teams of undergraduates work "around the clock" to discover and share meaning in a large, rich, and complex data set. It is a nationally coordinated weekend-long data analysis competition and challenges students to find their own story to tell with the data that is meaningful to the data donor.

At the competition, students received a large data set and were given less than 24 hours to create an executive summary report and five-minute presentation that tells a story from the data, complete with statistical analysis and interesting visualizations. Teams were asked to explore real, proprietary data.

**🏆 Best in Show Winner - 2024 & 2025**

At Truman, we had a group of four that worked on several smaller projects before the actual competition. Each year, we participated in both a practice DataFest and the actual competition, winning Best in Show in both 2024 and 2025.

Due to 4 people writing code with a limited timeframe, it is not in the cleanest format. I would recommend looking at the slideshow for our finished projects.

# Projects